spring.datasource.url=jdbc:postgresql://localhost:5432/wrenchlog_prod

spring.jpa.show-sql=true

file.upload-dir=./wrenchlog-uploads-dev
app.cors.allowed-origin=http://localhost:5173
app.cookie.secure=false

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.com.wrenchlog.wrenchlog.security=DEBUG
logging.level.org.springframework.security=DEBUG