spring.datasource.url=${DATABASE_URL}

spring.jpa.show-sql=false

file.upload-dir=${FILE_UPLOAD_DIR}
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}
app.cookie.secure=true

logging.level.org.flywaydb=WARN
logging.level.org.springframework.boot.autoconfigure.flyway=WARN
logging.level.com.wrenchlog.wrenchlog.security=WARN
logging.level.org.springframework.security=WARN