-- ============================================================
-- WrenchLog initial database schema
-- PostgreSQL
--
-- Creates:
--   users
--   vehicles
--   service_logs
--   service_reminders
--   vehicle_files
--   vehicle_notes
--   car_specifications
--
-- ============================================================


-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL,
                       email VARCHAR(100) NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,

                       CONSTRAINT uk_users_username UNIQUE (username),
                       CONSTRAINT uk_users_email UNIQUE (email)
);


-- ============================================================
-- VEHICLES
-- ============================================================

CREATE TABLE vehicles (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          make VARCHAR(50) NOT NULL,
                          model VARCHAR(50) NOT NULL,
                          production_year INTEGER,
                          kilometers INTEGER NOT NULL DEFAULT 0,
                          user_id BIGINT NOT NULL,

                          CONSTRAINT fk_vehicle_user
                              FOREIGN KEY (user_id)
                                  REFERENCES users(id)
                                  ON DELETE CASCADE,

                          CONSTRAINT chk_vehicle_kilometers_non_negative
                              CHECK (kilometers >= 0)
);


CREATE INDEX idx_vehicle_user_id
    ON vehicles(user_id);

-- ============================================================
-- SERVICE LOGS
-- ============================================================

CREATE TABLE service_logs (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              description VARCHAR(500) NOT NULL,

                              cost NUMERIC(10,2) NOT NULL DEFAULT 0,

                              kilometers_at_service INTEGER NOT NULL,

                              service_date DATE,

                              vehicle_id BIGINT NOT NULL,


                              CONSTRAINT fk_service_log_vehicle
                                  FOREIGN KEY (vehicle_id)
                                      REFERENCES vehicles(id)
                                      ON DELETE CASCADE,


                              CONSTRAINT chk_service_log_cost_non_negative
                                  CHECK (cost >= 0),


                              CONSTRAINT chk_service_log_kilometers_non_negative
                                  CHECK (kilometers_at_service >= 0)
);


CREATE INDEX idx_service_logs_vehicle_id
    ON service_logs(vehicle_id);

-- ============================================================
-- SERVICE REMINDERS
-- ============================================================

CREATE TABLE service_reminders (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   title VARCHAR(100) NOT NULL,
                                   description TEXT,
                                   last_service_at_odometer INTEGER,
                                   interval_odometer INTEGER,
                                   interval_months INTEGER,
                                   last_service_at_date DATE,
                                   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   vehicle_id BIGINT NOT NULL,

                                   CONSTRAINT fk_service_reminder_vehicle
                                       FOREIGN KEY (vehicle_id)
                                           REFERENCES vehicles(id)
                                           ON DELETE CASCADE,

                                   CONSTRAINT chk_last_service_odometer_non_negative
                                       CHECK (
                                           last_service_at_odometer IS NULL
                                               OR last_service_at_odometer >= 0
                                           ),

                                   CONSTRAINT chk_interval_odometer_non_negative
                                       CHECK (
                                           interval_odometer IS NULL
                                               OR interval_odometer >= 0
                                           ),

                                   CONSTRAINT chk_interval_months_non_negative
                                       CHECK (
                                           interval_months IS NULL
                                               OR interval_months >= 0
                                           )
);

CREATE INDEX idx_service_reminders_vehicle_id
    ON service_reminders(vehicle_id);

-- ============================================================
-- VEHICLE FILES
-- ============================================================

CREATE TABLE vehicle_files (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name VARCHAR(255) NOT NULL,
                               type VARCHAR(100) NOT NULL,
                               path VARCHAR(500) NOT NULL,
                               upload_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               vehicle_id BIGINT NOT NULL,

                               CONSTRAINT fk_vehicle_file_vehicle
                                   FOREIGN KEY (vehicle_id)
                                       REFERENCES vehicles(id)
                                       ON DELETE CASCADE
);

CREATE INDEX idx_vehicle_files_vehicle_id
    ON vehicle_files(vehicle_id);

-- ============================================================
-- VEHICLE NOTES
-- ============================================================

CREATE TABLE vehicle_notes (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               title VARCHAR(150) NOT NULL,
                               content TEXT,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               vehicle_id BIGINT NOT NULL,

                               CONSTRAINT fk_vehicle_note_vehicle
                                   FOREIGN KEY (vehicle_id)
                                       REFERENCES vehicles(id)
                                       ON DELETE CASCADE
);

CREATE INDEX idx_vehicle_notes_vehicle_id
    ON vehicle_notes(vehicle_id);

-- ============================================================
-- VEHICLE CATALOG / REFERENCE DATA
-- ============================================================

CREATE TABLE car_specifications (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    make VARCHAR(50),
                                    model VARCHAR(100),
                                    generation VARCHAR(100),
                                    modification VARCHAR(150),
                                    start_year INTEGER,
                                    end_year INTEGER
);

CREATE INDEX idx_car_specifications_make_model
    ON car_specifications(make, model);