CREATE TABLE electrical_components (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name VARCHAR(100) NOT NULL,
                                       description TEXT,
                                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       vehicle_id BIGINT NOT NULL,

                                       CONSTRAINT fk_electrical_component_vehicle
                                           FOREIGN KEY (vehicle_id)
                                               REFERENCES vehicles(id)
                                               ON DELETE CASCADE
);

CREATE INDEX idx_electrical_components_vehicle_id
    ON electrical_components(vehicle_id);


CREATE TABLE electrical_pins (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 name VARCHAR(100) NOT NULL,
                                 expected_range VARCHAR(100),
                                 component_id BIGINT NOT NULL,

                                 CONSTRAINT fk_electrical_pin_component
                                     FOREIGN KEY (component_id)
                                         REFERENCES electrical_components(id)
                                         ON DELETE CASCADE
);

CREATE INDEX idx_electrical_pins_component_id
    ON electrical_pins(component_id);


CREATE TABLE electrical_sessions (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     label VARCHAR(100) NOT NULL,
                                     session_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     notes TEXT,
                                     component_id BIGINT NOT NULL,

                                     CONSTRAINT fk_electrical_session_component
                                         FOREIGN KEY (component_id)
                                             REFERENCES electrical_components(id)
                                             ON DELETE CASCADE
);

CREATE INDEX idx_electrical_sessions_component_id
    ON electrical_sessions(component_id);


CREATE TABLE electrical_readings (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     value TEXT,
                                     unit VARCHAR(20),
                                     session_id BIGINT NOT NULL,
                                     pin_id BIGINT NOT NULL,

                                     CONSTRAINT fk_electrical_reading_session
                                         FOREIGN KEY (session_id)
                                             REFERENCES electrical_sessions(id)
                                             ON DELETE CASCADE,

                                     CONSTRAINT fk_electrical_reading_pin
                                         FOREIGN KEY (pin_id)
                                             REFERENCES electrical_pins(id)
                                             ON DELETE CASCADE,

                                     CONSTRAINT uk_reading_session_pin
                                         UNIQUE (session_id, pin_id)
);

CREATE INDEX idx_electrical_readings_session_id
    ON electrical_readings(session_id);

CREATE INDEX idx_electrical_readings_pin_id
    ON electrical_readings(pin_id);